modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="theyear3001"
version="1.0.0"
displayName="The Year 3001"
displayURL="https://www.nightbeam.cloud"
logoFile="logo.png"
credits="moonrayys <3"
authors="NightBeamStudio"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.theyear3001]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"


[[dependencies.theyear3001]]
modId="pehkui"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"
[[dependencies.theyear3001]]
modId="geckolib"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"
[[dependencies.theyear3001]]
modId="jei"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"


# Start of user code block dependencies configuration
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.0.3,)"
ordering="NONE"
side="BOTH"
# End of user code block dependencies configuration
