package tn.nightbeam.robotica.init;

import tn.nightbeam.robotica.item.TitaniumSwordItem;
import tn.nightbeam.robotica.item.TitaniumShovelItem;
import tn.nightbeam.robotica.item.TitaniumPickaxeItem;
import tn.nightbeam.robotica.item.TitaniumIngotItem;
import tn.nightbeam.robotica.item.TitaniumHoeItem;
import tn.nightbeam.robotica.item.TitaniumAxeItem;
import tn.nightbeam.robotica.item.TitaniumArmorItem;
import tn.nightbeam.robotica.item.SpeedUpgradeCardItem;
import tn.nightbeam.robotica.item.ScrapSwordItem;
import tn.nightbeam.robotica.item.ScrapShovelItem;
import tn.nightbeam.robotica.item.ScrapPickaxeItem;
import tn.nightbeam.robotica.item.ScrapItem;
import tn.nightbeam.robotica.item.ScrapHoeItem;
import tn.nightbeam.robotica.item.ScrapAxeItem;
import tn.nightbeam.robotica.item.ScrapArmorItem;
import tn.nightbeam.robotica.item.RepairCardItem;
import tn.nightbeam.robotica.item.RawTitaniumItem;
import tn.nightbeam.robotica.item.RawOrichalcumItem;
import tn.nightbeam.robotica.item.RawCobaltItem;
import tn.nightbeam.robotica.item.PrintedCircuitBoardItem;
import tn.nightbeam.robotica.item.OrichalcumSwordItem;
import tn.nightbeam.robotica.item.OrichalcumShovelItem;
import tn.nightbeam.robotica.item.OrichalcumPickaxeItem;
import tn.nightbeam.robotica.item.OrichalcumIngotItem;
import tn.nightbeam.robotica.item.OrichalcumHoeItem;
import tn.nightbeam.robotica.item.OrichalcumAxeItem;
import tn.nightbeam.robotica.item.OrichalcumArmorItem;
import tn.nightbeam.robotica.item.OilItem;
import tn.nightbeam.robotica.item.MechMK1EggItem;
import tn.nightbeam.robotica.item.FlyingCapsuleItem;
import tn.nightbeam.robotica.item.EmptyCardItem;
import tn.nightbeam.robotica.item.ElectricalConductorsItem;
import tn.nightbeam.robotica.item.DefenseUpgradeCardItem;
import tn.nightbeam.robotica.item.DamageUpgradeCardItem;
import tn.nightbeam.robotica.item.CobaltSwordItem;
import tn.nightbeam.robotica.item.CobaltShovelItem;
import tn.nightbeam.robotica.item.CobaltPickaxeItem;
import tn.nightbeam.robotica.item.CobaltIngotItem;
import tn.nightbeam.robotica.item.CobaltHoeItem;
import tn.nightbeam.robotica.item.CobaltAxeItem;
import tn.nightbeam.robotica.item.CobaltArmorItem;
import tn.nightbeam.robotica.item.CentralProcessingUnitItem;
import tn.nightbeam.robotica.item.BulkUpgradeCardItem;
import tn.nightbeam.robotica.item.BoggieMK1EggItem;
import tn.nightbeam.robotica.item.BlankPrintedCircuitBoardItem;
import tn.nightbeam.robotica.RoboticaMod;
import tn.nightbeam.robotica.RoboticaModNeoForge;

import net.neoforged.neoforge.registries.DeferredHolder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.neoforged.neoforge.registries.DeferredRegister;


import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

public class RoboticaModItemsNeoForge {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(BuiltInRegistries.ITEM, RoboticaMod.MOD_ID);
	public static final DeferredHolder<Item, Item> DAMAGE_UPGRADE_CARD = REGISTRY.register("damage_upgrade_card", () -> new DamageUpgradeCardItem());
	public static final DeferredHolder<Item, Item> OIL_BUCKET = REGISTRY.register("oil_bucket", () -> new OilItem());
	public static final DeferredHolder<Item, Item> BULK_UPGRADE_CARD = REGISTRY.register("bulk_upgrade_card", () -> new BulkUpgradeCardItem());
	public static final DeferredHolder<Item, Item> SPEED_UPGRADE_CARD = REGISTRY.register("speed_upgrade_card", () -> new SpeedUpgradeCardItem());
	public static final DeferredHolder<Item, Item> REPAIR_CARD = REGISTRY.register("repair_card", () -> new RepairCardItem());
	public static final DeferredHolder<Item, Item> SCRAP = REGISTRY.register("scrap", () -> new ScrapItem());
	public static final DeferredHolder<Item, Item> SCRAP_BLOCK = block(RoboticaModBlocksNeoForge.SCRAP_BLOCK);
	public static final DeferredHolder<Item, Item> CRAFTING_WORKSTATION = block(RoboticaModBlocksNeoForge.CRAFTING_WORKSTATION);
	public static final DeferredHolder<Item, Item> EMPTY_CARD = REGISTRY.register("empty_card", () -> new EmptyCardItem());
	public static final DeferredHolder<Item, Item> MECH_MK_1_EGG = REGISTRY.register("mech_mk_1_egg", () -> new MechMK1EggItem());
	public static final DeferredHolder<Item, Item> BOGGIE_MK_1_EGG = REGISTRY.register("boggie_mk_1_egg", () -> new BoggieMK1EggItem());
	public static final DeferredHolder<Item, Item> PRINTED_CIRCUIT_BOARD = REGISTRY.register("printed_circuit_board", () -> new PrintedCircuitBoardItem());
	public static final DeferredHolder<Item, Item> BLANK_PRINTED_CIRCUIT_BOARD = REGISTRY.register("blank_printed_circuit_board", () -> new BlankPrintedCircuitBoardItem());
	public static final DeferredHolder<Item, Item> CENTRAL_PROCESSING_UNIT = REGISTRY.register("central_processing_unit", () -> new CentralProcessingUnitItem());
	public static final DeferredHolder<Item, Item> ELECTRICAL_CONDUCTORS = REGISTRY.register("electrical_conductors", () -> new ElectricalConductorsItem());
	public static final DeferredHolder<Item, Item> DEFENSE_UPGRADE_CARD = REGISTRY.register("defense_upgrade_card", () -> new DefenseUpgradeCardItem());
	public static final DeferredHolder<Item, Item> SCRAP_AXE = REGISTRY.register("scrap_axe", () -> new ScrapAxeItem());
	public static final DeferredHolder<Item, Item> SCRAP_SWORD = REGISTRY.register("scrap_sword", () -> new ScrapSwordItem());
	public static final DeferredHolder<Item, Item> SCRAP_SHOVEL = REGISTRY.register("scrap_shovel", () -> new ScrapShovelItem());
	public static final DeferredHolder<Item, Item> SCRAP_HOE = REGISTRY.register("scrap_hoe", () -> new ScrapHoeItem());
	public static final DeferredHolder<Item, Item> SCRAP_PICKAXE = REGISTRY.register("scrap_pickaxe", () -> new ScrapPickaxeItem());
	public static final DeferredHolder<Item, Item> SCRAP_SLAB = block(RoboticaModBlocksNeoForge.SCRAP_SLAB);
	public static final DeferredHolder<Item, Item> SCRAP_STAIRS_BLOCK = block(RoboticaModBlocksNeoForge.SCRAP_STAIRS_BLOCK);
	public static final DeferredHolder<Item, Item> SPACE_SHIP_CAPSULE = REGISTRY.register("space_ship_capsule", () -> new FlyingCapsuleItem());
	public static final DeferredHolder<Item, Item> SCRAP_DEBRIS = block(RoboticaModBlocksNeoForge.SCRAP_DEBRIS);
	public static final DeferredHolder<Item, Item> TITANIUM_ORE = block(RoboticaModBlocksNeoForge.TITANIUM_ORE);
	public static final DeferredHolder<Item, Item> TITANIUM_INGOT = REGISTRY.register("titanium_ingot", () -> new TitaniumIngotItem());
	public static final DeferredHolder<Item, Item> ORICHALCUM_INGOT = REGISTRY.register("orichalcum_ingot", () -> new OrichalcumIngotItem());
	public static final DeferredHolder<Item, Item> COBALT_INGOT = REGISTRY.register("cobalt_ingot", () -> new CobaltIngotItem());
	public static final DeferredHolder<Item, Item> RAW_TITANIUM = REGISTRY.register("raw_titanium", () -> new RawTitaniumItem());
	public static final DeferredHolder<Item, Item> RAW_COBALT = REGISTRY.register("raw_cobalt", () -> new RawCobaltItem());
	public static final DeferredHolder<Item, Item> RAW_ORICHALCUM = REGISTRY.register("raw_orichalcum", () -> new RawOrichalcumItem());
	public static final DeferredHolder<Item, Item> COBALT_ORE = block(RoboticaModBlocksNeoForge.COBALT_ORE);
	public static final DeferredHolder<Item, Item> ORICHALCUM_ORE = block(RoboticaModBlocksNeoForge.ORICHALCUM_ORE);
	public static final DeferredHolder<Item, Item> TITANIUM_AXE = REGISTRY.register("titanium_axe", () -> new TitaniumAxeItem());
	public static final DeferredHolder<Item, Item> TITANIUM_SWORD = REGISTRY.register("titanium_sword", () -> new TitaniumSwordItem());
	public static final DeferredHolder<Item, Item> TITANIUM_SHOVEL = REGISTRY.register("titanium_shovel", () -> new TitaniumShovelItem());
	public static final DeferredHolder<Item, Item> TITANIUM_HOE = REGISTRY.register("titanium_hoe", () -> new TitaniumHoeItem());
	public static final DeferredHolder<Item, Item> TITANIUM_PICKAXE = REGISTRY.register("titanium_pickaxe", () -> new TitaniumPickaxeItem());
	public static final DeferredHolder<Item, Item> SCRAP_ARMOR_HELMET = REGISTRY.register("scrap_armor_helmet", () -> new ScrapArmorItem.Helmet());
	public static final DeferredHolder<Item, Item> SCRAP_ARMOR_CHESTPLATE = REGISTRY.register("scrap_armor_chestplate", () -> new ScrapArmorItem.Chestplate());
	public static final DeferredHolder<Item, Item> SCRAP_ARMOR_LEGGINGS = REGISTRY.register("scrap_armor_leggings", () -> new ScrapArmorItem.Leggings());
	public static final DeferredHolder<Item, Item> SCRAP_ARMOR_BOOTS = REGISTRY.register("scrap_armor_boots", () -> new ScrapArmorItem.Boots());
	public static final DeferredHolder<Item, Item> ORICHALCUM_ARMOR_HELMET = REGISTRY.register("orichalcum_armor_helmet", () -> new OrichalcumArmorItem.Helmet());
	public static final DeferredHolder<Item, Item> ORICHALCUM_ARMOR_CHESTPLATE = REGISTRY.register("orichalcum_armor_chestplate", () -> new OrichalcumArmorItem.Chestplate());
	public static final DeferredHolder<Item, Item> ORICHALCUM_ARMOR_LEGGINGS = REGISTRY.register("orichalcum_armor_leggings", () -> new OrichalcumArmorItem.Leggings());
	public static final DeferredHolder<Item, Item> ORICHALCUM_ARMOR_BOOTS = REGISTRY.register("orichalcum_armor_boots", () -> new OrichalcumArmorItem.Boots());
	public static final DeferredHolder<Item, Item> TITANIUM_ARMOR_HELMET = REGISTRY.register("titanium_armor_helmet", () -> new TitaniumArmorItem.Helmet());
	public static final DeferredHolder<Item, Item> TITANIUM_ARMOR_CHESTPLATE = REGISTRY.register("titanium_armor_chestplate", () -> new TitaniumArmorItem.Chestplate());
	public static final DeferredHolder<Item, Item> TITANIUM_ARMOR_LEGGINGS = REGISTRY.register("titanium_armor_leggings", () -> new TitaniumArmorItem.Leggings());
	public static final DeferredHolder<Item, Item> TITANIUM_ARMOR_BOOTS = REGISTRY.register("titanium_armor_boots", () -> new TitaniumArmorItem.Boots());
	public static final DeferredHolder<Item, Item> COBALT_ARMOR_HELMET = REGISTRY.register("cobalt_armor_helmet", () -> new CobaltArmorItem.Helmet());
	public static final DeferredHolder<Item, Item> COBALT_ARMOR_CHESTPLATE = REGISTRY.register("cobalt_armor_chestplate", () -> new CobaltArmorItem.Chestplate());
	public static final DeferredHolder<Item, Item> COBALT_ARMOR_LEGGINGS = REGISTRY.register("cobalt_armor_leggings", () -> new CobaltArmorItem.Leggings());
	public static final DeferredHolder<Item, Item> COBALT_ARMOR_BOOTS = REGISTRY.register("cobalt_armor_boots", () -> new CobaltArmorItem.Boots());
	public static final DeferredHolder<Item, Item> COBALT_AXE = REGISTRY.register("cobalt_axe", () -> new CobaltAxeItem());
	public static final DeferredHolder<Item, Item> COBALT_SWORD = REGISTRY.register("cobalt_sword", () -> new CobaltSwordItem());
	public static final DeferredHolder<Item, Item> COBALT_SHOVEL = REGISTRY.register("cobalt_shovel", () -> new CobaltShovelItem());
	public static final DeferredHolder<Item, Item> COBALT_HOE = REGISTRY.register("cobalt_hoe", () -> new CobaltHoeItem());
	public static final DeferredHolder<Item, Item> COBALT_PICKAXE = REGISTRY.register("cobalt_pickaxe", () -> new CobaltPickaxeItem());
	public static final DeferredHolder<Item, Item> ORICHALCUM_AXE = REGISTRY.register("orichalcum_axe", () -> new OrichalcumAxeItem());
	public static final DeferredHolder<Item, Item> ORICHALCUM_SWORD = REGISTRY.register("orichalcum_sword", () -> new OrichalcumSwordItem());
	public static final DeferredHolder<Item, Item> ORICHALCUM_SHOVEL = REGISTRY.register("orichalcum_shovel", () -> new OrichalcumShovelItem());
	public static final DeferredHolder<Item, Item> ORICHALCUM_HOE = REGISTRY.register("orichalcum_hoe", () -> new OrichalcumHoeItem());
	public static final DeferredHolder<Item, Item> ORICHALCUM_PICKAXE = REGISTRY.register("orichalcum_pickaxe", () -> new OrichalcumPickaxeItem());
	public static final DeferredHolder<Item, Item> SENTINEL_SPAWN_EGG = REGISTRY.register("sentinel_spawn_egg", () -> new Item(new Item.Properties().spawnEgg(RoboticaModEntitiesNeoForge.SENTINEL.get())));
	private static DeferredHolder<Item, Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredHolder<Item, Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}


	static {
		tn.nightbeam.robotica.init.RoboticaModItems.DAMAGE_UPGRADE_CARD = DAMAGE_UPGRADE_CARD;
		tn.nightbeam.robotica.init.RoboticaModItems.OIL_BUCKET = OIL_BUCKET;
		tn.nightbeam.robotica.init.RoboticaModItems.BULK_UPGRADE_CARD = BULK_UPGRADE_CARD;
		tn.nightbeam.robotica.init.RoboticaModItems.SPEED_UPGRADE_CARD = SPEED_UPGRADE_CARD;
		tn.nightbeam.robotica.init.RoboticaModItems.REPAIR_CARD = REPAIR_CARD;
		tn.nightbeam.robotica.init.RoboticaModItems.SCRAP = SCRAP;
		tn.nightbeam.robotica.init.RoboticaModItems.SCRAP_BLOCK = SCRAP_BLOCK;
		tn.nightbeam.robotica.init.RoboticaModItems.CRAFTING_WORKSTATION = CRAFTING_WORKSTATION;
		tn.nightbeam.robotica.init.RoboticaModItems.EMPTY_CARD = EMPTY_CARD;
		tn.nightbeam.robotica.init.RoboticaModItems.MECH_MK_1_EGG = MECH_MK_1_EGG;
		tn.nightbeam.robotica.init.RoboticaModItems.BOGGIE_MK_1_EGG = BOGGIE_MK_1_EGG;
		tn.nightbeam.robotica.init.RoboticaModItems.PRINTED_CIRCUIT_BOARD = PRINTED_CIRCUIT_BOARD;
		tn.nightbeam.robotica.init.RoboticaModItems.BLANK_PRINTED_CIRCUIT_BOARD = BLANK_PRINTED_CIRCUIT_BOARD;
		tn.nightbeam.robotica.init.RoboticaModItems.CENTRAL_PROCESSING_UNIT = CENTRAL_PROCESSING_UNIT;
		tn.nightbeam.robotica.init.RoboticaModItems.ELECTRICAL_CONDUCTORS = ELECTRICAL_CONDUCTORS;
		tn.nightbeam.robotica.init.RoboticaModItems.DEFENSE_UPGRADE_CARD = DEFENSE_UPGRADE_CARD;
		tn.nightbeam.robotica.init.RoboticaModItems.SCRAP_AXE = SCRAP_AXE;
		tn.nightbeam.robotica.init.RoboticaModItems.SCRAP_SWORD = SCRAP_SWORD;
		tn.nightbeam.robotica.init.RoboticaModItems.SCRAP_SHOVEL = SCRAP_SHOVEL;
		tn.nightbeam.robotica.init.RoboticaModItems.SCRAP_HOE = SCRAP_HOE;
		tn.nightbeam.robotica.init.RoboticaModItems.SCRAP_PICKAXE = SCRAP_PICKAXE;
		tn.nightbeam.robotica.init.RoboticaModItems.SCRAP_SLAB = SCRAP_SLAB;
		tn.nightbeam.robotica.init.RoboticaModItems.SCRAP_STAIRS_BLOCK = SCRAP_STAIRS_BLOCK;
		tn.nightbeam.robotica.init.RoboticaModItems.SPACE_SHIP_CAPSULE = SPACE_SHIP_CAPSULE;
		tn.nightbeam.robotica.init.RoboticaModItems.SCRAP_DEBRIS = SCRAP_DEBRIS;
		tn.nightbeam.robotica.init.RoboticaModItems.TITANIUM_ORE = TITANIUM_ORE;
		tn.nightbeam.robotica.init.RoboticaModItems.TITANIUM_INGOT = TITANIUM_INGOT;
		tn.nightbeam.robotica.init.RoboticaModItems.ORICHALCUM_INGOT = ORICHALCUM_INGOT;
		tn.nightbeam.robotica.init.RoboticaModItems.COBALT_INGOT = COBALT_INGOT;
		tn.nightbeam.robotica.init.RoboticaModItems.RAW_TITANIUM = RAW_TITANIUM;
		tn.nightbeam.robotica.init.RoboticaModItems.RAW_COBALT = RAW_COBALT;
		tn.nightbeam.robotica.init.RoboticaModItems.RAW_ORICHALCUM = RAW_ORICHALCUM;
		tn.nightbeam.robotica.init.RoboticaModItems.COBALT_ORE = COBALT_ORE;
		tn.nightbeam.robotica.init.RoboticaModItems.ORICHALCUM_ORE = ORICHALCUM_ORE;
		tn.nightbeam.robotica.init.RoboticaModItems.TITANIUM_AXE = TITANIUM_AXE;
		tn.nightbeam.robotica.init.RoboticaModItems.TITANIUM_SWORD = TITANIUM_SWORD;
		tn.nightbeam.robotica.init.RoboticaModItems.TITANIUM_SHOVEL = TITANIUM_SHOVEL;
		tn.nightbeam.robotica.init.RoboticaModItems.TITANIUM_HOE = TITANIUM_HOE;
		tn.nightbeam.robotica.init.RoboticaModItems.TITANIUM_PICKAXE = TITANIUM_PICKAXE;
		tn.nightbeam.robotica.init.RoboticaModItems.SCRAP_ARMOR_HELMET = SCRAP_ARMOR_HELMET;
		tn.nightbeam.robotica.init.RoboticaModItems.SCRAP_ARMOR_CHESTPLATE = SCRAP_ARMOR_CHESTPLATE;
		tn.nightbeam.robotica.init.RoboticaModItems.SCRAP_ARMOR_LEGGINGS = SCRAP_ARMOR_LEGGINGS;
		tn.nightbeam.robotica.init.RoboticaModItems.SCRAP_ARMOR_BOOTS = SCRAP_ARMOR_BOOTS;
		tn.nightbeam.robotica.init.RoboticaModItems.ORICHALCUM_ARMOR_HELMET = ORICHALCUM_ARMOR_HELMET;
		tn.nightbeam.robotica.init.RoboticaModItems.ORICHALCUM_ARMOR_CHESTPLATE = ORICHALCUM_ARMOR_CHESTPLATE;
		tn.nightbeam.robotica.init.RoboticaModItems.ORICHALCUM_ARMOR_LEGGINGS = ORICHALCUM_ARMOR_LEGGINGS;
		tn.nightbeam.robotica.init.RoboticaModItems.ORICHALCUM_ARMOR_BOOTS = ORICHALCUM_ARMOR_BOOTS;
		tn.nightbeam.robotica.init.RoboticaModItems.TITANIUM_ARMOR_HELMET = TITANIUM_ARMOR_HELMET;
		tn.nightbeam.robotica.init.RoboticaModItems.TITANIUM_ARMOR_CHESTPLATE = TITANIUM_ARMOR_CHESTPLATE;
		tn.nightbeam.robotica.init.RoboticaModItems.TITANIUM_ARMOR_LEGGINGS = TITANIUM_ARMOR_LEGGINGS;
		tn.nightbeam.robotica.init.RoboticaModItems.TITANIUM_ARMOR_BOOTS = TITANIUM_ARMOR_BOOTS;
		tn.nightbeam.robotica.init.RoboticaModItems.COBALT_ARMOR_HELMET = COBALT_ARMOR_HELMET;
		tn.nightbeam.robotica.init.RoboticaModItems.COBALT_ARMOR_CHESTPLATE = COBALT_ARMOR_CHESTPLATE;
		tn.nightbeam.robotica.init.RoboticaModItems.COBALT_ARMOR_LEGGINGS = COBALT_ARMOR_LEGGINGS;
		tn.nightbeam.robotica.init.RoboticaModItems.COBALT_ARMOR_BOOTS = COBALT_ARMOR_BOOTS;
		tn.nightbeam.robotica.init.RoboticaModItems.COBALT_AXE = COBALT_AXE;
		tn.nightbeam.robotica.init.RoboticaModItems.COBALT_SWORD = COBALT_SWORD;
		tn.nightbeam.robotica.init.RoboticaModItems.COBALT_SHOVEL = COBALT_SHOVEL;
		tn.nightbeam.robotica.init.RoboticaModItems.COBALT_HOE = COBALT_HOE;
		tn.nightbeam.robotica.init.RoboticaModItems.COBALT_PICKAXE = COBALT_PICKAXE;
		tn.nightbeam.robotica.init.RoboticaModItems.ORICHALCUM_AXE = ORICHALCUM_AXE;
		tn.nightbeam.robotica.init.RoboticaModItems.ORICHALCUM_SWORD = ORICHALCUM_SWORD;
		tn.nightbeam.robotica.init.RoboticaModItems.ORICHALCUM_SHOVEL = ORICHALCUM_SHOVEL;
		tn.nightbeam.robotica.init.RoboticaModItems.ORICHALCUM_HOE = ORICHALCUM_HOE;
		tn.nightbeam.robotica.init.RoboticaModItems.ORICHALCUM_PICKAXE = ORICHALCUM_PICKAXE;
		tn.nightbeam.robotica.init.RoboticaModItems.SENTINEL_SPAWN_EGG = SENTINEL_SPAWN_EGG;
	}
}
